[Theme]
Current=breeze
CursorTheme=breeze_cursors
Background=/usr/share/wallpapers/DurgaOS-Himalaya/contents/images/boudhanath_dusk.jpg

[Autologin]
User=durga
Session=plasma.desktop

[General]
Numlock=on
